### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Laky-64** [Squirrel-Network/gobotapi#5]
This GoBotAPI roadmap. If you have any requests feel free to leave them here/vote on others.

(There are listed only big change updates)

# 1.1.X (2022-05-26) - WIP
- [x] Plugins Support
- [x] Download Files
- [x] Handlers Context
- [x] Add Filters support
- [x] Upload & Download with Progress
- [ ] WebHook Support
- [ ] Passport, WebBot, Bot Login Decryptation
